# Generated by Django 2.1 on 2018-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('Lunes', 'lunes'), ('Martes', 'martes'), ('Miercoles', 'miercoles'), ('Jueves', 'jueves'), ('Viernes', 'viernes')], max_length=10),
        ),
    ]
