# Generated by Django 2.1 on 2018-09-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='lan',
        ),
    ]
