# Generated by Django 2.1 on 2018-09-21 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('course', '0003_auto_20180919_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
    ]
